#!/bin/bash
#-------------------------------------------------------------------------------
# Copyright (C) 2015-2018 Andreas Redmer <andreasredmer@mailchuck.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
#tf=`tempfile`
#gpg --debug-all --clearsign $tf
#gpg --clearsign $tf || exit 1
#rm -f $tf*
./licensecheck.sh || exit 1
./validateI18N.sh || exit 1
#./gradlew tests:test --info || exit 1

#update AUTHORS file
scripts/update-authors-file.sh || exit 1

#need to build the latest release apkm so the size is correct in status
# also ensuring that it actualyl builds it good
ANDROID_HOME=~/devel/android-sdk-linux/ ./gradlew assembleRelease || exit 1
scripts/update-project-status.sh || exit 1
