#!/bin/bash
#tf=`tempfile`
#gpg --debug-all --clearsign $tf
#gpg --clearsign $tf || exit 1
#rm -f $tf*
./licensecheck.sh || exit 1
./validateI18N.sh || exit 1
#./gradlew tests:test --info || exit 1

#update AUTHORS file
scripts/update-authors-file.sh || exit 1

#need to build the latest release apkm so the size is correct in status
# also ensuring that it actualyl builds it good
ANDROID_HOME=~/devel/android-sdk-linux/ ./gradlew assembleRelease || exit 1
scripts/update-project-status.sh || exit 1
