alone=1 skurwysyn
cancel=anuluj
chooseALevel=Wybieraj pierdolony poziom
clickAnAchievement=Klikaj na osiągnięcie, chuju
computer=Jebany komp
continue=Napierdalaj dalej
credits=Lista płac
default=domyślny
gameOver=PRZEJEBAŁEŚ
inputRequired=pisz, kurwa
itIsYourTurn=Dawaj, chuju
loading=idę po mleko
Music=Brzdękolenie
no=
okay=Dobra
PAUSE=FAIRANT
POINTS=PUNKCIORY
pleaseWait=Kurwa, czekaj
points=punkciory
programming=Kodoklep / Kreślarz / Brzdękacz / Poziomowiec
quitToMenu=Wypierdol do menu
reallyQuit=Wypierdalasz z gry czy nie?
restart=Jeszcze raz, kurwa
SoundFX=Brzdęki
touchScreenToContinue=Pierdolnij w ekran by kontynuować
